on:
  push:
    branches:
      - main

name: Deploy React App and Run Test

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: |
        npm install
      - name: Run test command
        run: |
        npm run test
      - name: Run Build
        run: |
        npm run build
          
