on:
  push:
    branches:
      - layout-style-additional-setup

name: Run Tests

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: npm ci, build and test
        run: |
        npm run build
        npm run test